version: '2'
services:
  redis:
    image: "redis:alpine"
    restart: always

  node:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - FOOD_ENV=DEV
      - FOOD_CHAT_GPT_API_KEY=${FOOD_CHAT_GPT_API_KEY}