services:
  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    restart: always
    ports:
      - "8191:8191"
    environment:
      - TZ=Europe/Vienna
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8191/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  flaresolverr-init:
    image: dhi.io/curl:${CURL_VERSION}
    depends_on:
      flaresolverr:
        condition: service_healthy
    command: >
      curl -L -X POST POST http://flaresolverr:8191/v1
      -H "Content-Type: application/json"
      -d '{"cmd": "sessions.create", "session": "baburu_session"}'