services:
  redis:
    image: redis:${REDIS_VERSION}
    restart: always

  node:
    build: ..
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      - FOOD_ENV=DEV
      - FOOD_LOG_LEVEL=debug
      - FOOD_REDIS_HOST=redis
      - FOOD_CHAT_GPT_API_KEY=${FOOD_CHAT_GPT_API_KEY}