services:
  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  flaresolverr:
    image: flaresolverr/flaresolverr:${FLARESOLVERR_VERSION}
    restart: always
    environment:
      - TZ=Europe/Vienna
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8191/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  flaresolverr-init:
    image: dhi.io/curl:${CURL_VERSION}
    depends_on:
      flaresolverr:
        condition: service_healthy
    command: >
      curl -L -X POST POST http://flaresolverr:8191/v1
      -H "Content-Type: application/json"
      -d '{"cmd": "sessions.create", "session": "baburu_session"}'
    links:
      - flaresolverr

  node:
    build: ..
    restart: always
    ports:
      - "3000:3000"
    links:
      - redis
      - flaresolverr
    environment:
      - FOOD_ENV=DEV
      - FOOD_LOG_LEVEL=debug
      - FOOD_REDIS_HOST=redis
      - FOOD_FLARESOLVERR_HOST=flaresolverr
      - FOOD_CHAT_GPT_API_KEY=${FOOD_CHAT_GPT_API_KEY}
    depends_on:
      redis:
        condition: service_healthy
      flaresolverr-init:
        condition: service_completed_successfully
