name: Deployment

on:
  push:
    branches:
      - master

jobs:
  artifact:
    name: Create artifact
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v3
      - name: Log in to private container registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_HOST }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        env:
          REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
          FOOD_CHAT_GPT_API_KEY: ${{ secrets.FOOD_CHAT_GPT_API_KEY }}
        run: |
          docker build . -t $REGISTRY_HOST/food:latest
          docker push $REGISTRY_HOST/food:latest
  deploy:
    name: Deploy with Docker Compose
    needs: [ artifact ]
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Run deployment script on Droplet on DigitalOcean via SSH
        uses: garygrossgarten/github-action-ssh@0.7.0
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
          command: ${{ secrets.SSH_COMMAND}}